also xfail test_maxiter_worsening for Python 3.10 on aarch64
see also https://github.com/scipy/scipy/issues/13019 + https://github.com/scipy/scipy/pull/13022
author: Kenneth Hoste (HPC-UGent) + Sebastian Achilles (Juelich Supercomputing Centre)
diff -ru scipy-1.11.1.orig/scipy/sparse/linalg/_isolve/tests/test_iterative.py scipy-1.11.1/scipy/sparse/linalg/_isolve/tests/test_iterative.py
--- scipy-1.11.1.orig/scipy/sparse/linalg/_isolve/tests/test_iterative.py       2023-07-28 07:18:00.387649832 +0000
+++ scipy-1.11.1/scipy/sparse/linalg/_isolve/tests/test_iterative.py    2023-07-29 18:17:22.432356816 +0000
@@ -465,7 +465,7 @@
     # which they should detect and halt as necessary.
     # cf. gh-9100
     if (solver is gmres and platform.machine() == 'aarch64'
-            and sys.version_info[1] == 9):
+            and sys.version_info[1] >= 9):
         pytest.xfail(reason="gh-13019")
     if (solver is lgmres and
             platform.machine() not in ['x86_64' 'x86', 'aarch64', 'arm64']):
